"""DNS compatibility vectors generated by dnslib (github.com/paulc/dnslib):
714 packets spanning every flag-bit combination, every (opcode, rcode) pair,
every (qtype, qclass) question combination, every (rtype, section, rclass)
RDATA combination, and several complex real-world-shaped scenarios (maximum
domain name length, maximum TXT segment, SOA field boundaries, root names,
all-sections-populated). Cross-checking against an independent DNS library's
own wire output is a much stronger correctness signal than only round-
tripping against ourselves -- byte-for-byte agreement here means our
`DNS`/`ResourceRecord`/RDATA encoders match RFC 1035 the same way dnslib
does, not just that pack() and unpack() happen to agree with each other.
"""

from __future__ import annotations

import json
from ipaddress import IPv4Address, IPv6Address
from itertools import product
from pathlib import Path
from typing import Any

import pytest

from rustruct.protocols.dns import (
    AAAA,
    CNAME,
    DNS,
    MX,
    NS,
    PTR,
    SOA,
    TXT,
    A,
    DNSClass,
    DNSFlags,
    Question,
    ResourceRecord,
    RRType,
    UnknownRData,
)

FIXTURE_PATH = Path(__file__).parents[1] / "fixtures" / "dnslib_dns_packets.json"
FIXTURE = json.loads(FIXTURE_PATH.read_text())
CASES = FIXTURE["cases"]

QUESTION_TYPES = {1, 2, 5, 6, 12, 15, 16, 28, 33, 41, 255, 65000}
DNS_CLASSES = {1, 3, 4, 255, 65000}
RDATA_TYPES = {1, 2, 5, 6, 12, 15, 16, 28, 65000}
SECTIONS = {"answers", "authorities", "additionals"}
SCENARIOS = {
    "all-questions-compressed",
    "all-rdata-all-sections",
    "maximum-domain-name",
    "maximum-txt-segment",
    "root-names",
    "scalar-boundaries",
    "soa-boundaries",
}


def decode_rdata(spec: dict[str, Any]) -> object:
    kind = spec["kind"]
    if kind == "A":
        return A(address=IPv4Address(spec["address"]))
    if kind == "AAAA":
        return AAAA(address=IPv6Address(spec["address"]))
    if kind == "NS":
        return NS(spec["target"])
    if kind == "CNAME":
        return CNAME(spec["target"])
    if kind == "PTR":
        return PTR(spec["target"])
    if kind == "MX":
        return MX(spec["preference"], spec["exchange"])
    if kind == "SOA":
        return SOA(
            spec["mname"],
            spec["rname"],
            spec["serial"],
            spec["refresh"],
            spec["retry"],
            spec["expire"],
            spec["minimum"],
        )
    if kind == "TXT":
        return TXT([bytes.fromhex(value) for value in spec["strings"]])
    if kind == "UnknownRData":
        return UnknownRData(spec["rtype"], bytes.fromhex(spec["data"]))
    raise AssertionError(f"unsupported fixture RDATA kind: {kind}")


def decode_question(spec: dict[str, Any]) -> Question:
    return Question(
        name=spec["name"],
        qtype=RRType(spec["qtype"]),
        qclass=DNSClass(spec["qclass"]),
    )


def decode_resource_record(spec: dict[str, Any]) -> ResourceRecord:
    data_spec = spec["data"]
    if data_spec["kind"] == "UnknownRData":
        data_spec = {**data_spec, "rtype": spec["rtype"]}
    # rtype is deliberately not a ResourceRecord field in rustruct (see its
    # docstring): it's derived from data.RTYPE / UnknownRData.rtype at pack
    # time, so passing it here would just be a third, redundant copy.
    return ResourceRecord(
        name=spec["name"],
        rclass=DNSClass(spec["rclass"]),
        ttl=spec["ttl"],
        data=decode_rdata(data_spec),
    )


def decode_packet(spec: dict[str, Any]) -> DNS:
    # qdcount/ancount/nscount/arcount are not DNS fields in rustruct either:
    # pack() always recomputes them from the section list lengths, so a
    # fixture's own count fields are only used implicitly, via those lengths.
    return DNS(
        id=spec["id"],
        flags=DNSFlags(**spec["flags"]),
        questions=[decode_question(value) for value in spec["questions"]],
        answers=[decode_resource_record(value) for value in spec["answers"]],
        authorities=[decode_resource_record(value) for value in spec["authorities"]],
        additionals=[decode_resource_record(value) for value in spec["additionals"]],
    )


@pytest.mark.parametrize("case", CASES, ids=[case["name"] for case in CASES])
def test_dnslib_packet_compatibility(case: dict[str, Any]) -> None:
    wire = bytes.fromhex(case["wire"])
    packet = decode_packet(case["packet"])

    assert packet.pack() == wire
    assert DNS.unpack(wire).pack() == wire


def coverage(family: str, *axes: str) -> set[tuple[Any, ...]]:
    return {tuple(case["coverage"][axis] for axis in axes) for case in CASES if case["coverage"]["family"] == family}


def test_dnslib_fixture_provenance_and_unique_names() -> None:
    assert FIXTURE["schema"] == 1
    assert FIXTURE["generated_by"] == {
        "library": "dnslib",
        "repository": "https://github.com/paulc/dnslib",
        "version": "0.9.26",
    }
    names = [case["name"] for case in CASES]
    assert len(names) == len(set(names)) == 714


def test_dnslib_fixture_covers_every_flag_combination() -> None:
    assert coverage("flag-bits", "boolean_mask", "z") == set(product(range(32), range(8)))
    assert coverage("opcode-rcode", "opcode", "rcode") == set(product(range(16), repeat=2))


def test_dnslib_fixture_covers_every_question_combination() -> None:
    assert coverage("question", "qtype", "qclass") == set(product(QUESTION_TYPES, DNS_CLASSES))


def test_dnslib_fixture_covers_every_rdata_combination() -> None:
    assert coverage("rdata", "rtype", "section", "rclass") == set(product(RDATA_TYPES, SECTIONS, DNS_CLASSES))


def test_dnslib_fixture_covers_complex_scenarios() -> None:
    assert {value[0] for value in coverage("scenario", "scenario")} == SCENARIOS
