"""DNS compatibility vectors generated by dnslib (github.com/paulc/dnslib):
909 packets spanning every flag-bit combination, every (opcode, rcode) pair,
every (qtype, qclass) question combination, every (rtype, section, rclass)
RDATA combination across all 21 implemented record types (the original
eight rustruct.protocols.dns started with, plus the thirteen added later:
SRV/NAPTR/DNAME/RP/RRSIG/NSEC/DS/DNSKEY/TLSA/SSHFP/CAA/HTTPS/LOC) plus one
placeholder standing in for an unregistered type (UnknownRData), and
several complex real-world-shaped scenarios (maximum domain name length,
maximum TXT segment, SOA field boundaries, root names, all-sections-
populated). Cross-checking against an independent DNS library's own wire
output is a much stronger correctness signal than only round-tripping
against ourselves -- byte-for-byte agreement here means our
`DNS`/`ResourceRecord`/RDATA encoders match RFC 1035 the same way dnslib
does, not just that pack() and unpack() happen to agree with each other.

The whole fixture is regenerated from scratch by
tests/fixtures/generate_dns_fixtures.py (dnslib is not one of this
package's own dependencies, so that generator needs a separate interpreter
with dnslib installed -- it is not part of this test suite).
"""

from __future__ import annotations

import json
from ipaddress import IPv4Address, IPv6Address
from itertools import product
from pathlib import Path
from typing import Any

import pytest

from rustruct.protocols.dns import (
    AAAA,
    CAA,
    CNAME,
    DNAME,
    DNS,
    DNSKEY,
    DS,
    HTTPS,
    LOC,
    MX,
    NAPTR,
    NS,
    NSEC,
    PTR,
    RP,
    RRSIG,
    SOA,
    SRV,
    SSHFP,
    TLSA,
    TXT,
    A,
    DNSClass,
    DNSFlags,
    Question,
    ResourceRecord,
    RRType,
    UnknownRData,
)

FIXTURE_PATH = Path(__file__).parents[1] / "fixtures" / "dnslib_dns_packets.json"
FIXTURE = json.loads(FIXTURE_PATH.read_text())
CASES = FIXTURE["cases"]

QUESTION_TYPES = {1, 2, 5, 6, 12, 15, 16, 28, 33, 41, 255, 65000}
DNS_CLASSES = {1, 3, 4, 255, 65000}
RDATA_TYPES = {1, 2, 5, 6, 12, 15, 16, 28, 17, 29, 33, 35, 39, 43, 44, 46, 47, 48, 52, 65, 257, 65000}
SECTIONS = {"answers", "authorities", "additionals"}
SCENARIOS = {
    "all-questions-compressed",
    "all-rdata-all-sections",
    "maximum-domain-name",
    "maximum-txt-segment",
    "root-names",
    "scalar-boundaries",
    "soa-boundaries",
}


def decode_rdata(spec: dict[str, Any]) -> object:
    match spec["kind"]:
        case "A":
            return A(address=IPv4Address(spec["address"]))
        case "AAAA":
            return AAAA(address=IPv6Address(spec["address"]))
        case "NS":
            return NS(spec["target"])
        case "CNAME":
            return CNAME(spec["target"])
        case "PTR":
            return PTR(spec["target"])
        case "MX":
            return MX(spec["preference"], spec["exchange"])
        case "SOA":
            return SOA(
                spec["mname"],
                spec["rname"],
                spec["serial"],
                spec["refresh"],
                spec["retry"],
                spec["expire"],
                spec["minimum"],
            )
        case "TXT":
            return TXT([bytes.fromhex(value) for value in spec["strings"]])
        case "SRV":
            return SRV(spec["priority"], spec["weight"], spec["port"], spec["target"])
        case "NAPTR":
            return NAPTR(
                spec["order"], spec["preference"], spec["flags"], spec["service"], spec["regexp"], spec["replacement"]
            )
        case "DNAME":
            return DNAME(spec["target"])
        case "RP":
            return RP(spec["mbox"], spec["txt"])
        case "RRSIG":
            return RRSIG(
                spec["type_covered"],
                spec["algorithm"],
                spec["labels"],
                spec["original_ttl"],
                spec["expiration"],
                spec["inception"],
                spec["key_tag"],
                spec["signer"],
                bytes.fromhex(spec["signature"]),
            )
        case "NSEC":
            return NSEC(spec["next_domain"], spec["rrtypes"])
        case "DS":
            return DS(
                key_tag=spec["key_tag"],
                algorithm=spec["algorithm"],
                digest_type=spec["digest_type"],
                digest=bytes.fromhex(spec["digest"]),
            )
        case "DNSKEY":
            return DNSKEY(
                flags=spec["flags"],
                protocol=spec["protocol"],
                algorithm=spec["algorithm"],
                key=bytes.fromhex(spec["key"]),
            )
        case "TLSA":
            return TLSA(
                usage=spec["usage"],
                selector=spec["selector"],
                matching_type=spec["matching_type"],
                cert_data=bytes.fromhex(spec["cert_data"]),
            )
        case "SSHFP":
            return SSHFP(
                algorithm=spec["algorithm"], fp_type=spec["fp_type"], fingerprint=bytes.fromhex(spec["fingerprint"])
            )
        case "CAA":
            return CAA(flags=spec["flags"], tag=spec["tag"], value=spec["value"])
        case "HTTPS":
            return HTTPS(
                spec["priority"], spec["target"], [(key, bytes.fromhex(value)) for key, value in spec["params"]]
            )
        case "LOC":
            return LOC(
                latitude=spec["latitude"],
                longitude=spec["longitude"],
                altitude=spec["altitude"],
                size=spec["size"],
                h_precision=spec["h_precision"],
                v_precision=spec["v_precision"],
            )
        case "UnknownRData":
            return UnknownRData(spec["rtype"], bytes.fromhex(spec["data"]))
        case kind:
            raise AssertionError(f"unsupported fixture RDATA kind: {kind}")


def decode_question(spec: dict[str, Any]) -> Question:
    return Question(
        name=spec["name"],
        qtype=RRType(spec["qtype"]),
        qclass=DNSClass(spec["qclass"]),
    )


def decode_resource_record(spec: dict[str, Any]) -> ResourceRecord:
    data_spec = spec["data"]
    if data_spec["kind"] == "UnknownRData":
        data_spec = {**data_spec, "rtype": spec["rtype"]}
    # rtype is deliberately not a ResourceRecord field in rustruct (see its
    # docstring): it's derived from data.RTYPE / UnknownRData.rtype at pack
    # time, so passing it here would just be a third, redundant copy.
    return ResourceRecord(
        name=spec["name"],
        rclass=DNSClass(spec["rclass"]),
        ttl=spec["ttl"],
        data=decode_rdata(data_spec),
    )


def decode_packet(spec: dict[str, Any]) -> DNS:
    # qdcount/ancount/nscount/arcount are not DNS fields in rustruct either:
    # pack() always recomputes them from the section list lengths, so a
    # fixture's own count fields are only used implicitly, via those lengths.
    return DNS(
        id=spec["id"],
        flags=DNSFlags(**spec["flags"]),
        questions=[decode_question(value) for value in spec["questions"]],
        answers=[decode_resource_record(value) for value in spec["answers"]],
        authorities=[decode_resource_record(value) for value in spec["authorities"]],
        additionals=[decode_resource_record(value) for value in spec["additionals"]],
    )


@pytest.mark.parametrize("case", CASES, ids=[case["name"] for case in CASES])
def test_dnslib_packet_compatibility(case: dict[str, Any]) -> None:
    wire = bytes.fromhex(case["wire"])
    packet = decode_packet(case["packet"])

    assert packet.pack() == wire
    assert DNS.unpack(wire).pack() == wire


def coverage(family: str, *axes: str) -> set[tuple[Any, ...]]:
    return {tuple(case["coverage"][axis] for axis in axes) for case in CASES if case["coverage"]["family"] == family}


def test_dnslib_fixture_provenance_and_unique_names() -> None:
    assert FIXTURE["schema"] == 1
    assert FIXTURE["generated_by"] == {
        "library": "dnslib",
        "repository": "https://github.com/paulc/dnslib",
        "version": "0.9.26",
    }
    names = [case["name"] for case in CASES]
    assert len(names) == len(set(names)) == 909


def test_dnslib_fixture_covers_every_flag_combination() -> None:
    assert coverage("flag-bits", "boolean_mask", "z") == set(product(range(32), range(8)))
    assert coverage("opcode-rcode", "opcode", "rcode") == set(product(range(16), repeat=2))


def test_dnslib_fixture_covers_every_question_combination() -> None:
    assert coverage("question", "qtype", "qclass") == set(product(QUESTION_TYPES, DNS_CLASSES))


def test_dnslib_fixture_covers_every_rdata_combination() -> None:
    assert coverage("rdata", "rtype", "section", "rclass") == set(product(RDATA_TYPES, SECTIONS, DNS_CLASSES))


def test_dnslib_fixture_covers_complex_scenarios() -> None:
    assert {value[0] for value in coverage("scenario", "scenario")} == SCENARIOS
